import type { Metadata } from "next";
import "./globals.css";
import NavBar from '@/components/NavBar';
import {satoshi, monument} from "../font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth md:overflow-y-scroll ">
      <body className={` relative ${monument.variable} ${satoshi.variable}`}>
      <NavBar />
      {children}
      </body>

    </html>
  );
}
